/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.kpodvolecky.less;

import com.github.kpodvolecky.less.configuration.GradleLessExtension;
import org.gradle.api.Project;
import org.gradle.api.Plugin;

/**
 * A simple 'hello world' plugin.
 */
public class GradleLessPlugin implements Plugin<Project> {
    public void apply(Project project) {
        GradleLessExtension extension = project.getExtensions()
                .create("lessCompiler", GradleLessExtension.class);

        // Register a task
        project.getTasks().register("lessCompile", LessCompileTask.class);
    }
}
